### ISSUE TITLE
flare

### ISSUE THREAD

**Issue by Nathan-Kr** [PerdrieauC/MasterMind#3]
package com.company;
import javax.swing.*;
import java.awt.*;
import java.awt.geom.Point2D;

public class Main extends JFrame{
    public Main(){
        setTitle("Drawing a Circle");
        setSize(400, 400);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
        
        g.setColor(Color.red);
        //g2d.fillOval(150, 150, 100, 100);
        Point2D center = new Point2D.Float(210, 170);
        float radius = 100;
        float[] dist = {0.00f, .40f};
        Color[] colors = {Color.white, Color.red};
        RadialGradientPaint paint = new RadialGradientPaint(center, radius, dist, colors, MultipleGradientPaint.CycleMethod.REFLECT);
        g2d.setPaint(paint);
        g2d.fillOval(150, 150, 100, 100);

    }
    public static void main(String[] args) {
	    new Main();
    }
}

**Comment by Kroissan** [comment]
public void drawCircle(Graphics2D g2d, int x, int y, Color c){
        int radius = 200;
        int shadowSize = 2*radius/100; //2%

        Point2D center = new Point2D.Float(x-shadowSize+radius/2, y+shadowSize+radius/2);
        Color b = new Color(0xFF000000, true); //using colors with transparency!!!
        Color w = new Color(0x00FFFFFF, true);
        RadialGradientPaint paint = new RadialGradientPaint(center, radius, new float[]{0.4f, 0.5f}, new Color[]{b, w}, MultipleGradientPaint.CycleMethod.NO_CYCLE);
        g2d.setPaint(paint);
        g2d.fillOval(x-shadowSize, y+shadowSize, radius, radius);

        center = new Point2D.Double(x+radius*0.7, y+radius*0.3);
        float[] dist = {0.00f, 0.4f, 0.95f};
        Color[] colors = {Color.white, c, c.darker()};
        paint = new RadialGradientPaint(center, radius, dist, colors, MultipleGradientPaint.CycleMethod.REFLECT);
        g2d.setPaint(paint);
        g2d.fillOval(x, y, radius, radius);
    }
